project_name: configarr
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - ldflags:
      - -s -w -X github.com/graytonio/configarr/cmd.VersionString={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - image_templates:
      - ghcr.io/graytonio/configarr:latest
      - ghcr.io/graytonio/configarr:{{ .Tag }}

