# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:
    cmds:
      - goreleaser build --snapshot --rm-dist --single-target
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
